server:
   port: 8090
   servlet:
    context-path: /blog
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/
#      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: springboot
    password: 12345
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false